"""empty message

Revision ID: 1d548af42928
Revises: 47098808e376
Create Date: 2017-08-31 00:02:02.219000

"""

# revision identifiers, used by Alembic.
revision = '1d548af42928'
down_revision = '47098808e376'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_interested',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('id_item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_item'], ['tbl_item.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['tbl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'tbl_category', 'id_category')
    op.drop_column(u'tbl_item', 'id_item')
    op.drop_column(u'tbl_users', 'userid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'tbl_users', sa.Column('userid', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column(u'tbl_item', sa.Column('id_item', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'tbl_category', sa.Column('id_category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('tbl_interested')
    ### end Alembic commands ###
