"""empty message

Revision ID: 2ddc0db957a2
Revises: None
Create Date: 2017-08-20 11:46:33.616000

"""

# revision identifiers, used by Alembic.
revision = '2ddc0db957a2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=35), nullable=False),
    sa.Column('firstname', sa.String(length=150), nullable=True),
    sa.Column('lastname', sa.String(length=150), nullable=False),
    sa.Column('birthdate', sa.DATE(), nullable=False),
    sa.Column('registerdate', sa.TIMESTAMP(), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_users')
    ### end Alembic commands ###
