"""empty message

Revision ID: 33ac513415ea
Revises: 4c4d30ce63ec
Create Date: 2017-09-10 18:38:59.355000

"""

# revision identifiers, used by Alembic.
revision = '33ac513415ea'
down_revision = '4c4d30ce63ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_category', sa.Column('img_category', sa.String(length=100), nullable=False))
    op.add_column('tbl_item', sa.Column('img_item', sa.String(length=100), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_item', 'img_item')
    op.drop_column('tbl_category', 'img_category')
    ### end Alembic commands ###
