"""empty message

Revision ID: 45556be315cf
Revises: 2d3a7f133159
Create Date: 2017-09-21 16:26:27.866000

"""

# revision identifiers, used by Alembic.
revision = '45556be315cf'
down_revision = '2d3a7f133159'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('isLogin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'isLogin')
    ### end Alembic commands ###
