"""empty message

Revision ID: 48a34fbbe398
Revises: 134c4f5725b0
Create Date: 2017-09-08 18:25:23.037000

"""

# revision identifiers, used by Alembic.
revision = '48a34fbbe398'
down_revision = '134c4f5725b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_users', 'isactive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tbl_users', 'registerdate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tbl_users', 'updateDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_users', 'updateDate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tbl_users', 'registerdate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tbl_users', 'isactive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###
