"""empty message

Revision ID: 500f4b5ce7be
Revises: 45556be315cf
Create Date: 2017-09-22 01:22:03.159000

"""

# revision identifiers, used by Alembic.
revision = '500f4b5ce7be'
down_revision = '45556be315cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_interested', sa.Column('id_category', sa.Integer(), nullable=True))
    op.drop_constraint(u'tbl_interested_id_item_fkey', 'tbl_interested', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_interested', 'tbl_category', ['id_category'], ['id'])
    op.drop_column('tbl_interested', 'id_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_interested', sa.Column('id_item', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tbl_interested', type_='foreignkey')
    op.create_foreign_key(u'tbl_interested_id_item_fkey', 'tbl_interested', 'tbl_item', ['id_item'], ['id'])
    op.drop_column('tbl_interested', 'id_category')
    ### end Alembic commands ###
